group 'net.touchcapture.qr.flutterqrplus'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    compileSdk 36

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        // minSdkVersion is determined by Native View.
        minSdkVersion 20
        targetSdkVersion 36
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    compileOptions {
        // Flag to enable support for the new language APIs
        // // // coreLibraryDesugaringEnabled true
        // Sets Java compatibility to Java 17
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    if (project.android.hasProperty('namespace')) {
        namespace 'net.touchcapture.qr.flutterqrplus'
    }
}

dependencies {
    implementation('com.journeyapps:zxing-android-embedded:4.3.0') { transitive = false }
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.zxing:core:3.5.2'
    // // // coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.3'
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}
